name: Deploy Plugin to NPM
on:
  push:
    paths:
      - plugin
      - pnpm-lock.yaml
    tags:
      - v?\d+.\d+.\d+

jobs:
  Build-And-Deploy:
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ensure tag is on master
        run: |
          TAG_COMMIT=$(git rev-list -n 1 $GITHUB_REF)
          MASTER_COMMIT=$(git rev-parse origin/master)

          if [ "$TAG_COMMIT" != "$MASTER_COMMIT" ]; then
            echo "‚ùå Tag is not on master"
            exit 1
          fi
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Install Dependencies
        run: pnpm install --filter postcss-glitch
      - name: Build
        run: pnpm --filter postcss-glitch build:ci
      - name: Check secret
        run: |
          echo "NODE_AUTH_TOKEN length: ${#NODE_AUTH_TOKEN}"
          pnpm whoami
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to NPM
        run: pnpm --filter postcss-glitch publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
