name: Publish Plugin to NPM
on:
  push:
    paths:
      - plugin
      - pnpm-lock.yaml
    tags:
      - v?\d+.\d+.\d+

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  Build-And-Publish:
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Ensure tag is on master
        run: |
          TAG_COMMIT=$(git rev-list -n 1 $GITHUB_REF)
          MASTER_COMMIT=$(git rev-parse origin/master)

          if [ "$TAG_COMMIT" != "$MASTER_COMMIT" ]; then
            echo "‚ùå Tag is not on master"
            exit 1
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Dependencies
        run: pnpm install --filter postcss-glitch
      - name: Build
        run: pnpm --filter postcss-glitch build:ci
      - name: Publish to NPM
        run: pnpm --filter postcss-glitch publish --access public --no-git-checks
