name: Run linters and tests for Demo
on:
  push:
  pull_request:

jobs:
  Run-Tests-For-Demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Dependencies
        run: pnpm install --filter simple
      - name: Run ESLint
        run: pnpm --filter simple lint
      - name: Run Unit Tests
        run: pnpm --filter simple test

